var systemDictionary = {
    "Heating": {
        "en": "Heating",
        "de": "Heiztechnik",
        "ru": "Отопительная техника",
        "pt": "Tecnologia de aquecimento",
        "nl": "verwarmingstechnologie",
        "fr": "Technologie de chauffage",
        "it": "tecnologia di riscaldamento",
        "es": "tecnología de calefacción",
        "pl": "technologia grzewcza",
        "zh-cn": "加热技术"
    },
    "Connection": {
        "en": "Connection",
        "de": "Verbindung",
        "ru": "Соединение",
        "pt": "Conexão",
        "nl": "Verbinding",
        "fr": "Connexion",
        "it": "Connessione",
        "es": "Conexión",
        "pl": "Połączenie",
        "zh-cn": "连接"
    },
    "Adapter IP:": {
        "en": "Adapter IP:",
        "de": "Adapter IP:",
        "ru": "IP адаптера:",
        "pt": "IP do adaptador:",
        "nl": "Adapter IP:",
        "fr": "Adaptateur IP:",
        "it": "IP adattatore:",
        "es": "IP del adaptador:",
        "pl": "Adapter IP:",
        "zh-cn": "适配器IP："
    },
    "Port:": {
        "en": "Port:",
        "de": "Port:",
        "ru": "Порт:",
        "pt": "Porta:",
        "nl": "Haven:",
        "fr": "Port:",
        "it": "Porta:",
        "es": "Puerto:",
        "pl": "Port:",
        "zh-cn": "港口："
    },
    "Status as Bool": {
        "en": "Status as Bool",
        "de": "Status als Bool",
        "ru": "Статус как Bool",
        "pt": "Status como Bool",
        "nl": "Status als Bool",
        "fr": "Statut en tant que Bool",
        "it": "Stato come Bool",
        "es": "Estado como bool",
        "pl": "Status jako Bool",
        "zh-cn": "身份为布尔"
    },
    "Pressure in bar": {
        "en": "Pressure in bar",
        "de": "Druck in bar",
        "ru": "Давление в барах",
        "pt": "Pressão em bar",
        "nl": "Druk in bar",
        "fr": "Pression en bar",
        "it": "Pressione in bar",
        "es": "Presión en bar",
        "pl": "Ciśnienie w barach",
        "zh-cn": "压力（巴）"
    },
    "ON": {
        "en": "ON",
        "de": "EIN",
        "ru": "ВКЛ",
        "pt": "EM",
        "nl": "OP",
        "fr": "SUR",
        "it": "SU",
        "es": "EN",
        "pl": "NA",
        "zh-cn": "上"
    },
    "Heaters": {
        "en": "Heaters",
        "de": "Heizgeräte",
        "ru": "Обогреватели",
        "pt": "Aquecedores",
        "nl": "Kachels",
        "fr": "Chauffages",
        "it": "Riscaldatori",
        "es": "Calentadores",
        "pl": "Grzejniki",
        "zh-cn": "加热器"
    },
    "Auto": {
        "en": "Auto",
        "de": "Auto",
        "ru": "Aвто",
        "pt": "Auto",
        "nl": "Auto",
        "fr": "Auto",
        "it": "Auto",
        "es": "Auto",
        "pl": "Auto",
        "zh-cn": "Auto"
    },
    "off": {
        "en": "off",
        "de": "aus",
        "ru": "от",
        "pt": "fora",
        "nl": "uit",
        "fr": "de",
        "it": "via",
        "es": "apagado",
        "pl": "poza",
        "zh-cn": "关"
    },
    "Devices": {
        "en": "Devices",
        "de": "Geräte",
        "ru": "приборы",
        "pt": "Aparelhos",
        "nl": "Apparaten",
        "fr": "Dispositifs",
        "it": "dispositivi",
        "es": "Dispositivos",
        "pl": "Urządzenia",
        "zh-cn": "设备"
    },
    "Name": {
        "en": "Name",
        "de": "Name",
        "ru": "Название",
        "pt": "Nome",
        "nl": "Naam",
        "fr": "Prénom",
        "it": "Nome",
        "es": "Nombre",
        "pl": "Imię",
        "zh-cn": "名称"
    },
    "Operating modules": {
        "en": "Operating modules",
        "de": "Bedienmodule",
        "ru": "Операционные модули",
        "pt": "Módulos de operação",
        "nl": "Bedieningsmodules",
        "fr": "Modules d'exploitation",
        "it": "Moduli operativi",
        "es": "Módulos operativos",
        "pl": "Moduły operacyjne",
        "zh-cn": "操作模块"
    },
    "Mixing modules": {
        "en": "Mixing modules",
        "de": "Mischmodul",
        "ru": "Модули микширования",
        "pt": "Módulo de mistura",
        "nl": "Mengmodule",
        "fr": "Module de mixage",
        "it": "Modulo di miscelazione",
        "es": "Módulo de mezcla",
        "pl": "Moduł mieszający",
        "zh-cn": "混合模块"
    },
    "Cascade modules": {
        "en": "Cascade modules",
        "de": "Kaskadenmodule",
        "ru": "Каскадные модули",
        "pt": "Módulo em cascata",
        "nl": "Cascademodule",
        "fr": "Module en cascade",
        "it": "Modulo a cascata",
        "es": "Módulo en cascada",
        "pl": "Moduł kaskadowy",
        "zh-cn": "级联模块"
    },
    "Solar cells": {
        "en": "Solar cells",
        "de": "Solarzelle",
        "ru": "Солнечная батарея",
        "pt": "Célula solar",
        "nl": "Zonnecel",
        "fr": "Cellule photovoltaïque",
        "it": "Celle a energia solare",
        "es": "Célula solar",
        "pl": "Ogniwo słoneczne",
        "zh-cn": "太阳能电池"
    },
    "Comfort domestic ventilation system": {
        "en": "Comfort domestic ventilation system",
        "de": "Comfort-Wohnungs-Lüftung",
        "ru": "Комфортная система домашней вентиляции",
        "pt": "Sistema de ventilação doméstica Comfort",
        "nl": "Comfort huishoudelijk ventilatiesysteem",
        "fr": "Système de ventilation domestique confort",
        "it": "Comfort sistema di ventilazione domestica",
        "es": "Sistema de ventilación doméstica confort",
        "pl": "Komfortowy system wentylacji domowej",
        "zh-cn": "舒适的家用通风系统"
    },
    "Split air/water heat pump": {
        "en": "Split air/water heat pump",
        "de": "Split-Luft/Wasser-Wärmepumpe",
        "ru": "Сплит воздушный/водяной тепловой насос",
        "pt": "Bomba de calor split ar / água",
        "nl": "Split lucht / water warmtepomp",
        "fr": "Pompe à chaleur air / eau split",
        "it": "Pompa di calore split aria / acqua",
        "es": "Split bomba de calor aire / agua",
        "pl": "Podzielona pompa ciepła powietrze / woda",
        "zh-cn": "分体式空气/水热泵"
    }
};
