/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Adapter IP:": {                                 "en": "Adapter Bind Interface",                          "de": "Adapter Bind Schnittstelle",                      "ru": "Интерфейс привязки адаптера",                     "pt": "Interface de ligação do adaptador",               "nl": "Adapter Bind Interface",                          "fr": "Interface de liaison de l'adaptateur",            "it": "Interfaccia di collegamento dell'adattatore",     "es": "Interfaz de enlace del adaptador",                "pl": "Interfejs powiązania adaptera",                   "zh-cn": "适配器绑定接口"},
    "Auto": {                                        "en": "Auto",                                            "de": "Auto",                                            "ru": "Aвто",                                            "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto",                                            "pl": "Auto",                                            "zh-cn": "Auto"},
    "Cascade modules": {                             "en": "Cascade modules",                                 "de": "Kaskadenmodule",                                  "ru": "Каскадные модули",                                "pt": "Módulo em cascata",                               "nl": "Cascademodule",                                   "fr": "Module en cascade",                               "it": "Modulo a cascata",                                "es": "Módulo en cascada",                               "pl": "Moduł kaskadowy",                                 "zh-cn": "级联模块"},
    "Comfort domestic ventilation system": {         "en": "Comfort domestic ventilation system",             "de": "Comfort-Wohnungs-Lüftung",                        "ru": "Комфортная система домашней вентиляции",          "pt": "Sistema de ventilação doméstica Comfort",         "nl": "Comfort huishoudelijk ventilatiesysteem",         "fr": "Système de ventilation domestique confort",       "it": "Comfort sistema di ventilazione domestica",       "es": "Sistema de ventilación doméstica confort",        "pl": "Komfortowy system wentylacji domowej",            "zh-cn": "舒适的家用通风系统"},
    "Connection": {                                  "en": "Connection",                                      "de": "Verbindung",                                      "ru": "Соединение",                                      "pt": "Conexão",                                         "nl": "Verbinding",                                      "fr": "Connexion",                                       "it": "Connessione",                                     "es": "Conexión",                                        "pl": "Połączenie",                                      "zh-cn": "连接"},
    "Devices": {                                     "en": "Devices",                                         "de": "Geräte",                                          "ru": "приборы",                                         "pt": "Aparelhos",                                       "nl": "Apparaten",                                       "fr": "Dispositifs",                                     "it": "dispositivi",                                     "es": "Dispositivos",                                    "pl": "Urządzenia",                                      "zh-cn": "设备"},
    "Heaters": {                                     "en": "Heaters",                                         "de": "Heizgeräte",                                      "ru": "Обогреватели",                                    "pt": "Aquecedores",                                     "nl": "Kachels",                                         "fr": "Chauffages",                                      "it": "Riscaldatori",                                    "es": "Calentadores",                                    "pl": "Grzejniki",                                       "zh-cn": "加热器"},
    "Heating": {                                     "en": "Heating",                                         "de": "Heiztechnik",                                     "ru": "Отопительная техника",                            "pt": "Tecnologia de aquecimento",                       "nl": "verwarmingstechnologie",                          "fr": "Technologie de chauffage",                        "it": "tecnologia di riscaldamento",                     "es": "tecnología de calefacción",                       "pl": "technologia grzewcza",                            "zh-cn": "加热技术"},
    "IP Hint": {                                     "en": "Please make sure to select an Bind interface that allows external connections!", "de": "Bitte eine Bind-Schnittstelle auswählen, die externe Verbindungen zulässt!", "ru": "Обязательно выберите интерфейс Bind, который разрешает внешние подключения!", "pt": "Certifique-se de selecionar uma interface Bind que permita conexões externas!", "nl": "Zorg ervoor dat u een Bind-interface selecteert die externe verbindingen mogelijk maakt!", "fr": "Assurez-vous de sélectionner une interface Bind qui autorise les connexions externes !", "it": "Assicurati di selezionare un'interfaccia Bind che consenta connessioni esterne!", "es": "¡Asegúrese de seleccionar una interfaz Bind que permita conexiones externas!", "pl": "Upewnij się, że wybrałeś interfejs Bind, który umożliwia połączenia zewnętrzne!", "zh-cn": "请务必选择允许外部连接的绑定接口！"},
    "Mixing modules": {                              "en": "Mixing modules",                                  "de": "Mischmodul",                                      "ru": "Модули микширования",                             "pt": "Módulo de mistura",                               "nl": "Mengmodule",                                      "fr": "Module de mixage",                                "it": "Modulo di miscelazione",                          "es": "Módulo de mezcla",                                "pl": "Moduł mieszający",                                "zh-cn": "混合模块"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Название",                                        "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Prénom",                                          "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię",                                            "zh-cn": "名称"},
    "ON": {                                          "en": "ON",                                              "de": "EIN",                                             "ru": "ВКЛ",                                             "pt": "EM",                                              "nl": "OP",                                              "fr": "SUR",                                             "it": "SU",                                              "es": "EN",                                              "pl": "NA",                                              "zh-cn": "上"},
    "Operating modules": {                           "en": "Operating modules",                               "de": "Bedienmodule",                                    "ru": "Операционные модули",                             "pt": "Módulos de operação",                             "nl": "Bedieningsmodules",                               "fr": "Modules d'exploitation",                          "it": "Moduli operativi",                                "es": "Módulos operativos",                              "pl": "Moduły operacyjne",                               "zh-cn": "操作模块"},
    "Port:": {                                       "en": "Port:",                                           "de": "Port:",                                           "ru": "Порт:",                                           "pt": "Porta:",                                          "nl": "Haven:",                                          "fr": "Port:",                                           "it": "Porta:",                                          "es": "Puerto:",                                         "pl": "Port:",                                           "zh-cn": "港口："},
    "Pressure in bar": {                             "en": "Pressure in bar",                                 "de": "Druck in bar",                                    "ru": "Давление в барах",                                "pt": "Pressão em bar",                                  "nl": "Druk in bar",                                     "fr": "Pression en bar",                                 "it": "Pressione in bar",                                "es": "Presión en bar",                                  "pl": "Ciśnienie w barach",                              "zh-cn": "压力（巴）"},
    "Solar cells": {                                 "en": "Solar cells",                                     "de": "Solarzelle",                                      "ru": "Солнечная батарея",                               "pt": "Célula solar",                                    "nl": "Zonnecel",                                        "fr": "Cellule photovoltaïque",                          "it": "Celle a energia solare",                          "es": "Célula solar",                                    "pl": "Ogniwo słoneczne",                                "zh-cn": "太阳能电池"},
    "Split air/water heat pump": {                   "en": "Split air/water heat pump",                       "de": "Split-Luft/Wasser-Wärmepumpe",                    "ru": "Сплит воздушный/водяной тепловой насос",          "pt": "Bomba de calor split ar / água",                  "nl": "Split lucht / water warmtepomp",                  "fr": "Pompe à chaleur air / eau split",                 "it": "Pompa di calore split aria / acqua",              "es": "Split bomba de calor aire / agua",                "pl": "Podzielona pompa ciepła powietrze / woda",        "zh-cn": "分体式空气/水热泵"},
    "Status as Bool": {                              "en": "Status as Boolean",                               "de": "Status als Boolean",                              "ru": "Статус как логический",                           "pt": "Status como booleano",                            "nl": "Status als Booleaans",                            "fr": "Statut booléen",                                  "it": "Stato come booleano",                             "es": "Estado como booleano",                            "pl": "Status jako Boolean",                             "zh-cn": "布尔值状态"},
    "off": {                                         "en": "off",                                             "de": "aus",                                             "ru": "от",                                              "pt": "fora",                                            "nl": "uit",                                             "fr": "de",                                              "it": "via",                                             "es": "apagado",                                         "pl": "poza",                                            "zh-cn": "关"},
};